# -*- coding: utf-8 -*-
"""ML_corn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U71kTuvQah3n2uEWxRU8jqtbMBv-wlsh

# Satellite-based Crop Classification using Google Earth Engine Python API
การติดตั้งและ Authentication
"""

#pip install earthengine-api --upgrade

import ee
ee.Authenticate()
ee.Initialize(project='coastal-wares-439106-s9')

!pip install mlflow

import geemap
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

"""# **กำหนดพื้นที่สนใจ (AOI)**"""

aoi = ee.Geometry.Rectangle([98.03724813148085, 18.32740564041369, 98.36821126624648, 18.67642400421453])

#ช่วงฤดูเพาะปลูก
crop_season_start = '2024-05-01'
crop_season_end = '2025-02-28'

print(f"Crop season: {crop_season_start} to {crop_season_end}")
print(f"AOI bounds: {aoi.bounds().getInfo()}")

# แสดงพื้นที่บนแผนที่
Map = geemap.Map()
Map.centerObject(aoi, zoom=9)
Map.addLayer(aoi, {'color': 'red'}, 'AOI')
Map

"""## **Sentinel-1 Data Collection**"""

def get_sentinel1_data(crop_season_start, crop_season_end, aoi):
    """ดึงข้อมูล Sentinel-1"""
    sen1_raw = ee.ImageCollection('COPERNICUS/S1_GRD') \
        .filterBounds(aoi) \
        .filterDate(crop_season_start, crop_season_end) \
        .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV')) \
        .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH')) \
        .filter(ee.Filter.eq('instrumentMode', 'IW')) \
        .select(['VV', 'VH'])

    print(f"Sentinel1_image: {sen1_raw.size().getInfo()}")
    return sen1_raw

"""# **Sentinel-2 Data Collection**"""

def get_sentinel2_data(crop_season_start, crop_season_end, aoi):
    """ดึงข้อมูล Sentinel-2"""
    sen2_raw = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED') \
        .filterBounds(aoi) \
        .filterDate(crop_season_start, crop_season_end) \
        .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 30)) \
        .select(['B2', 'B3', 'B4', 'B8', 'B11', 'B12'])

    print(f"Sentinel2_image: {sen2_raw.size().getInfo()}")
    return sen2_raw

"""สร้าง Monthly Composite หมายถึงการรวมภาพถ่ายดาวเทียมหลายๆ ภาพที่ถ่ายในเดือนเดียวกันให้เป็นภาพเดียว เพื่อให้ได้ภาพที่สมบูรณ์และคุณภาพดีกว่าการใช้ภาพเดี่ยวทำไมต้องทำ Monthly Composite?
แก้ปัญหาเมฆ: ภาพดาวเทียมมักมีเมฆบัง การรวมหลายภาพช่วยให้ได้พื้นที่ที่ใสจากเมฆมากขึ้น
เพิ่มความครอบคลุม: บางครั้งดาวเทียมไม่ได้ถ่ายครอบคลุมพื้นที่ทั้งหมดในภาพเดียว
ลดสัญญาณรบกวน: การรวมภาพช่วยลดความผิดเพี้ยนจากบรรยากาศ
ได้ภาพที่เหมาะสมที่สุด: ใช้ค่าเฉลี่ย, มัธยฐาน, หรือค่าที่ดีที่สุดจากหลายภาพ

# **S1 Composite (VV, VH, Diff, Ratio)**

S1 หมายถึง Sentinel-1 ดาวเทียม SAR (Synthetic Aperture Radar) ของ ESA ที่สามารถถ่ายภาพได้ทุกสภาพอากาศ กลางวันกลางคืน

*   การประยุกต์ใช้
*   VV: ดีสำหรับตรวจจับผิวน้ำ, พื้นที่เปิด
*   VH: ดีสำหรับวิเคราะห์พืชพรรณ, ป่าไม้
*   Diff: ช่วยแยกแยะเขตเมือง vs พื้นที่ธรรมชาติ
*   Ratio: วิเคราะห์ความหนาแน่นของพืชพรรณ
"""

# สร้างลิสต์เดือนสำหรับ Composite รายเดือน
# เดือน 5-12 (พ.ค.-ธ.ค.) ต่อด้วยเดือน 1-2 (ม.ค.-ก.พ.)

months = ee.List(list(range(5, 13))).cat(ee.List(list(range(1, 3))))
print(months.getInfo())

"""#Feature Engineering"""

# สร้าง Monthly Composite
def create_monthly_composites(s1_raw, s2_raw, months_list):
    """สร้าง composite รายเดือน"""

    # S1 Monthly Composites with derived indices
    def create_s1_monthly(month):
        month = ee.Number(month)

        year = ee.Algorithms.If(month.lte(2), 2025, 2024);
        start = ee.Date.fromYMD(year, month, 1);
        end = start.advance(1, 'month');

        # คำนวณค่าเฉลี่ยรายเดือน
        img = ee.Image(s1_raw.filterDate(crop_season_start, crop_season_end).mean())
        band_names = img.bandNames()
        month_str = month.format('%02d')

        # ฟังก์ชันสำหรับสร้าง bands ทั้งหมด (เมื่อมีทั้ง VV และ VH)
        def create_bands():
            vv = img.select('VV')
            vh = img.select('VH')
            diff = vh.subtract(vv)  # VH - VV
            ratio = vh.divide(vv)   # VH / VV

            name_vv = ee.String('S1VV_').cat(month_str)
            name_vh = ee.String('S1VH_').cat(month_str)
            name_diff = ee.String('S1Diff_').cat(month_str)
            name_ratio = ee.String('S1Ratio_').cat(month_str)

            return vv.rename([name_vv]) \
                .addBands(vh.rename([name_vh])) \
                .addBands(diff.rename([name_diff])) \
                .addBands(ratio.rename([name_ratio]))

        # เช็คว่ามี VV และ VH หรือไม่ ก่อนสร้าง bands
        return ee.Algorithms.If(
            band_names.contains('VV'),
            ee.Algorithms.If(
                band_names.contains('VH'),
                create_bands(),
                None
            ),
            None
        )

    # Map ฟังก์ชันกับทุกเดือน
    s1_raw = months_list.map(create_s1_monthly)

    # กรองค่า None ออก (เดือนที่ไม่มีข้อมูล)
    s1_raw= ee.List(s1_raw).removeAll([None])

    return s1_raw

# Get Sentinel data
s1_raw = get_sentinel1_data(crop_season_start, crop_season_end, aoi)
s2_raw = get_sentinel2_data(crop_season_start, crop_season_end, aoi)

# ใช้งาน
s1_monthly = create_monthly_composites(s1_raw, s2_raw, months)
print("จำนวน S1 composite ที่สร้างได้:", s1_monthly.size().getInfo())

# ดูชื่อ band ของภาพแรก
if s1_monthly.size().getInfo() > 0:
    first_image = ee.Image(s1_monthly.get(0))
    print("Band names ของภาพแรก:", first_image.bandNames().getInfo())

# แปลงเป็น single composite image
s1_composite = ee.ImageCollection.fromImages(s1_monthly) \
    .filter(ee.Filter.notNull(['system:band_names'])) \
    .toBands()

# ดูจำนวน bands ทั้งหมด
band_names = s1_composite.bandNames().getInfo()
print(f"S1_Composite มีทั้งหมด {len(band_names)} bands")
print("Band names:", band_names)

# เพิ่มโค้ดนี้เพื่อดูว่าแต่ละเดือนมีข้อมูลไหม
def check_monthly_data(s1_raw, months_list):
    for m in [5, 6, 7, 8, 9, 10, 11, 12, 1, 2]:
        month = ee.Number(m)
        start = ee.Date('2024-01-01').advance(month.subtract(1), 'month')
        end = start.advance(1, 'month')
        count = s1_raw.filterDate(start, end).size().getInfo()
        print(f"เดือน {m:02d}: มี {count} รูป")

check_monthly_data(s1_raw, months)

"""สรุป: ได้ 8 เดือนเพราะมี 2 เดือนที่ไม่มีข้อมูล Sentinel-1 หรือข้อมูลเดือนนั้นมีไม่ครบ VV+VH อาจมีอันใดอันหนึ่ง

#S2 Composite + Vegetation Indices (NDVI, SAVI, NDMI)

*   B4 = Red (สำหรับ NDVI, SAVI)
*   B8 = Near-Infrared/NIR (สำหรับ NDVI, SAVI, NDMI)
*   B11 = Shortwave Infrared/SWIR (สำหรับ NDMI)
"""

def process_month_s2(m, s2_raw):
  month = ee.Number(m)
  year = ee.Algorithms.If(month.lte(2), 2025, 2024);
  start = ee.Date.fromYMD(year, month, 1);
  end = start.advance(1, 'month');

 #คำนวณ median ของเดือนนั้นๆ
  img = s2_raw.filterDate(start, end).median()

 #สร้าง month string
  month_str = month.format('%02d')

 #ตรวจสอบว่ามี band ครบไหมนำค่าที่หาค่ากลางมาเฉลี่ย
  band_names = img.bandNames() # Corrected from bandName()

 # ขั้นตอนที่ 2: กำหนด bands ที่จำเป็นต้องมี
  required_bands = ee.List(['B4', 'B8', 'B11'])

 # ขั้นตอนที่ 3: ตรวจสอบทีละ band ว่ามีครบไหม
  def check_band(b, prev):
    return ee.Algorithms.If(prev, band_names.contains(b), False)
  has_all_bands = required_bands.iterate(check_band, True) # Corrected indentation

  def create_indices():
    #คำนวณ NDVI (Normalized Difference)
    ndvi = img.normalizedDifference(['B8','B4']).rename( # Corrected parenthesis
        ee.String('NDVI_').cat(month_str) # Corrected month_Str to month_str
    )
    #คำนวณ NDMI (Normalized Differ)
    ndmi = img.normalizedDifference(['B8', 'B11']).rename( # Corrected parenthesis
        ee.String('NDMI_').cat(month_str) # Corrected month_Str to month_str
    )

    #คำนวณ SAVI (Soil - Adjusted Index)
    savi = img.expression(
        '((NIR - RED) / (NIR + RED + L)) * (1 + L)', { # Corrected expression and indentation
            'NIR' : img.select('B8'),
            'RED' : img.select('B4'),
            'L':0.5
        }
    ).rename(ee.String('SAVI_').cat(month_str)) # Corrected indentation

    #เปลี่ยนชื่อแบนด์ ของภาพหลักให้มี prefix และ suffix
    def rename_band(band):
      return ee.String('S2_').cat(band).cat('_').cat(month_str)
    renamed = img.rename(img.bandNames().map(rename_band)) # Corrected indentation

    #รวม bands ทั้งหมดเข้าด้วยกัน
    result = renamed.addBands(ndvi).addBands(savi).addBands(ndmi) # Corrected indentation
    return result # Corrected indentation

  #ส่งคืนผลลัพธ์ หรือ None ถ้าไม่มี bands ครบ
  return ee.Algorithms.If(has_all_bands, create_indices(), None) # Corrected If and indentation

#สร้าง list ของ image สำหรับแต่ละเดือน
s2_monthly_list = months.map(lambda m: process_month_s2(m, s2_raw))

#สร้าง comcoposite โดยรวม bands เข้าด้วยกัน
s2_composite = (ee.ImageCollection.fromImages(s2_monthly_list)
        .filter(ee.Filter.notNull(['system:band_names']))
        .toBands())

#ดูจำนวน  bands ทั้งหมด
band_names_s2 = s2_composite.bandNames().getInfo() # Corrected band_names_s2
print(f"S2 Composite มีทั้งหมด {len(band_names_s2)} bands")
print("Band names:", band_names_s2)

"""ทำการรวม (combine) bands จาก Sentinel-1 และ Sentinel-2 เข้าด้วยกัน แล้ว reproject ให้อยู่ในระบบพิกัด UTM Zone 47N (EPSG:32647) ที่ resolution 10 เมตร

# **Combine แล้ว Reproject ให้เหมือน**
"""

monthly_composite_all = s1_composite.addBands(s2_composite)\
    .reproject(crs = 'EPSG:32647', scale=10)

#ตรวจสอบ  band name
print('Band names:', monthly_composite_all.bandNames().getInfo())

"""# Self-training: KMeans บน sample จากภาพ และ Self - label

*   ทำการสุ่มตัวอย่าง 5000 จุด
*  ภาพดาวเทียมมีข้อมูลเยอะมาก ถ้าเอาทั้งหมดมาวิเคราะห์จะช้าและใช้ทรัพยากรมาก


*   สร้างตัวแบ่งกลุ่ม (Clusterer) แบบ KMeans ที่แบ่งเป็น 5 กลุ่ม
*   ใช้ข้อมูล 5,000 จุดที่สุ่มมาเพื่อ "เรียนรู้" ว่าแต่ละกลุ่มมีลักษณะยังไง


*   หาจุดศูนย์กลาง (Centroid) ของแต่ละกลุ่ม จัดพิกเซลที่มีค่าใกล้เคียงกันให้อยู่กลุ่มเดียวกัน
*   ทำซ้ำจนกว่าจะหากลุ่มที่เหมาะสมที่สุด





"""

# Self-training: KMeans Clustering
sample = monthly_composite_all.sample(
    region=aoi,
    scale=10,
    numPixels=5000,
    seed=42,
    geometries=True
)

clusterer = ee.Clusterer.wekaKMeans(5).train(sample)

#นำไปใช้กับภาพทั้งหมด (Classification)
cluster_image = monthly_composite_all.cluster(clusterer)

# Check Cluster Distribution
cluster_hist = cluster_image.reduceRegion(
    reducer=ee.Reducer.frequencyHistogram(),
    geometry=aoi,
    scale=10,
    maxPixels=1e9
)
print('Cluster Distribution:', cluster_hist.getInfo())

#Self-labeling
#สำคัญ: ต้องดู cluster distribution แล้วเลือก cluster ที่เป็นข้าวโพด

corn_cluster_id = 2  # เปลี่ยนตามผลที่ได้จากการวิเคราะห์

corn_mask = cluster_image.eq(corn_cluster_id)
non_corn_mask = cluster_image.neq(corn_cluster_id)

corn_pixels = cluster_image.updateMask(corn_mask).rename('class').multiply(0).add(1)
non_corn_pixels = cluster_image.updateMask(non_corn_mask).rename('class').multiply(0)

label_image = corn_pixels.unmask().add(non_corn_pixels.unmask()).rename('class')

"""#Train Classifier"""

# Train Classifier
training = monthly_composite_all.addBands(label_image).sample(
    region=aoi,          #สุ่มจุดข้อมูลจากพื้นที่ที่กำหนด (aoi)
    scale=10,
    numPixels=5000,      #สุ่ม 5,000 จุด
    seed=42              #กำหนด random seed เพื่อให้ได้ผลเหมือนเดิมทุกครั้ง
)

class_dist = training.aggregate_histogram('class').getInfo()
print('Class distribution in training:', class_dist)

#แบ่ง train - test (70:30)
split = 0.7
withRandom = training.randomColumn('random', 999)
trainSet =  withRandom.filter(ee.Filter.lt('random', split))
testSet = withRandom.filter(ee.Filter.gte('random', split))

print('Training set size:', trainSet.size().getInfo())
print('Test set size:', testSet.size().getInfo())

#Train Random Forest
classifierRF = (ee.Classifier.smileRandomForest(
    numberOfTrees=50,
    minLeafPopulation=5)
    .train(
        features=training,
        classProperty='class',
        inputProperties=monthly_composite_all.bandNames()
    ))

#SVM Classification
classifierSVM = ee.Classifier.libsvm(
    kernelType= 'RBF',
    gamma = 0.5,
    cost = 10
).train(
    features=training,
    classProperty = 'class',
    inputProperties=monthly_composite_all.bandNames()
)

"""# รวม predictions จาก RF และ SVM
def ensemble_prediction(classifiedRF, classifiedSVM, weights=[0.6, 0.4]):
    '''
    Soft voting ensemble
    Weight ตาม validation accuracy
    '''
    # Convert to probability-like scores
    rf_score = classifiedRF.multiply(weights[0])
    svm_score = classifiedSVM.multiply(weights[1])
    
    # Combine
    ensemble = rf_score.add(svm_score)
    final_class = ensemble.gt(0.5)  # threshold = 0.5
    
    return final_class

# Evaluate Model

# เพิ่ม metrics เพิ่มเติม
def calculate_comprehensive_metrics(confusion_matrix):
    '''คำนวณ metrics ครบถ้วน'''
    cm = confusion_matrix.getInfo()
    
    # คำนวณ per-class metrics
    tp = cm[1][1]  # True Positive (Corn)
    tn = cm[0][0]  # True Negative (Non-corn)
    fp = cm[0][1]  # False Positive
    fn = cm[1][0]  # False Negative
    
    metrics = {
        'accuracy': (tp + tn) / (tp + tn + fp + fn),
        'precision': tp / (tp + fp) if (tp + fp) > 0 else 0,
        'recall': tp / (tp + fn) if (tp + fn) > 0 else 0,
        'f1_score': 2 * tp / (2 * tp + fp + fn) if (2 * tp + fp + fn) > 0 else 0,
        'specificity': tn / (tn + fp) if (tn + fp) > 0 else 0
    }
    
    return metrics
"""

# ทำนายบน Test Set
validatedRF = testSet.classify(classifierRF)
print('validatedRF:', validatedRF.getInfo())

validatedSVM = testSet.classify(classifierSVM)
print('validatedSVM:', validatedRF.getInfo())

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# ดึง Confusion Matrix
confusionMatrixRF = validatedRF.errorMatrix('class', 'classification')
cm_array1 = confusionMatrixRF.getInfo()

confusionMatrixSVM = validatedSVM.errorMatrix('class', 'classification')
cm_array2 = confusionMatrixSVM.getInfo()

# สร้าง Heatmap สำหรับ Random Forest
plt.figure(figsize=(8, 6))
class_names = ['Non-Corn', 'Corn']

sns.heatmap(cm_array1, annot=True, fmt='g', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names,
            cbar_kws={'label': 'Count'})

plt.title('Confusion Matrix (Random Forest)', fontsize=16, fontweight='bold')
plt.xlabel('Predicted Class', fontsize=12)
plt.ylabel('Actual Class', fontsize=12)
plt.tight_layout()
plt.show()

# สร้าง Heatmap สำหรับ SVM
plt.figure(figsize=(8, 6))
sns.heatmap(cm_array2, annot=True, fmt='g', cmap='Greens',
            xticklabels=class_names, yticklabels=class_names,
            cbar_kws={'label': 'Count'})

plt.title('Confusion Matrix (SVM)', fontsize=16, fontweight='bold')
plt.xlabel('Predicted Class', fontsize=12)
plt.ylabel('Actual Class', fontsize=12)
plt.tight_layout()
plt.show()


# แสดงค่าความแม่นยำ
print(f"\n--- Random Forest Metrics ---")
print(f"Overall Accuracy: {confusionMatrixRF.accuracy().getInfo():.4f}")
print(f"Kappa: {confusionMatrixRF.kappa().getInfo():.4f}")

print(f"\n--- SVM Metrics ---")
print(f"Overall Accuracy: {confusionMatrixSVM.accuracy().getInfo():.4f}")
print(f"Kappa: {confusionMatrixSVM.kappa().getInfo():.4f}")

"""#ทำนายบนภาพดาวเทียม"""

# Prediction of Random Forest
classifiedRF = monthly_composite_all.classify(classifierRF)
corn_only_RF = classifiedRF.updateMask(classifiedRF.eq(1))

# Prediction of Support Vector Machine
classifiedSVM = monthly_composite_all.classify(classifierSVM)
corn_only_SVM = classifiedSVM.updateMask(classifiedSVM.eq(1))

# Prediction of Random Forest
classifiedRF = monthly_composite_all.classify(classifierRF)
corn_only_RF = classifiedRF.updateMask(classifiedRF.eq(1))

#Calculate Area for Random Forest
corn_area_RF = corn_only_RF.multiply(ee.Image.pixelArea()).reduceRegion(
    reducer=ee.Reducer.sum(),
    geometry=aoi,
    scale=10,
    maxPixels=1e9,
    bestEffort=True # Add bestEffort to prevent timeout
)

area_sqm_RF = corn_area_RF.getInfo().get('classification', 0)
area_hectares_RF = area_sqm_RF / 10000
area_rai_RF = area_hectares_RF * 6.25  # 1 hectare = 6.25 rai


print(f'--- Corn Area Results ---')
print(f'Corn area RF: {area_sqm_RF:,.0f} m²')
print(f'Corn area RF: {area_hectares_RF:,.2f} hectares')
print(f'Corn area RF: {area_rai_RF:,.2f} rai')


# Post-processing
# 1. Smooth with Majority Filter
smoothed_RF = corn_only_RF.focal_mode(radius=1, kernelType='square')

# 2. Remove Small Patches
connected = corn_only_RF.connectedPixelCount(50)
filtered = corn_only_RF.updateMask(connected.gte(10))

# Visualization with geemap
Map = geemap.Map()
Map.centerObject(aoi, 15)
Map.setOptions('HYBRID')

# Add layers
Map.addLayer(cluster_image, {
    'min': 0,
    'max': 4,
    'palette': ['red', 'blue', 'green', 'orange', 'purple']
}, 'Clusters')

Map.addLayer(corn_only_RF.clip(aoi), {'palette': ['yellow']}, 'Corn (Random Forest)')
Map.addLayer(filtered.clip(aoi), {'palette': ['lime']}, 'Corn (Filtered)')

s2_median = s2_raw.median()
Map.addLayer(s2_median, {'bands': ['B4','B3','B2'], 'max': 3000}, 'True Color')

# Display map
Map

# Export to Google Drive (Optional)

# Uncomment เพื่อ export ผลลัพธ์
task = ee.batch.Export.image.toDrive(
    image=filtered,
    description='corn_classification__2024',
    scale=10,
    region=aoi,
    fileFormat='GeoTIFF',
    maxPixels=1e9
)
task.start()
print('\nExport task started. Check your Google Drive.')

# Prediction of Support Vector Machine
classifiedSVM = monthly_composite_all.classify(classifierSVM)
corn_only_SVM = classifiedSVM.updateMask(classifiedSVM.eq(1))

#Calculate Area for Support Vector Machine
corn_area_SVM = corn_only_SVM.multiply(ee.Image.pixelArea()).reduceRegion(
    reducer=ee.Reducer.sum(),
    geometry=aoi,
    scale=50,          # ปรับจาก 30 → 50 เพื่อให้เร็วขึ้น
    maxPixels=1e13,
    bestEffort=True,
    tileScale=8
)


area_sqm_SVM = corn_area_SVM.getInfo().get('classification', 0)
area_hectares_SVM = area_sqm_SVM / 10000
area_rai_SVM = area_hectares_SVM * 6.25  # 1 hectare = 6.25 rai


print(f'Corn area SVM: {area_sqm_SVM:,.0f} m²')
print(f'Corn area SVM: {area_hectares_SVM:,.2f} hectares')
print(f'Corn area SVM: {area_rai_SVM:,.2f} rai')


# Post-processing
# 1. Smooth with Majority Filter
smoothed_SVM = corn_only_SVM.focal_mode(radius=1, kernelType='square')

# 2. Remove Small Patches (Applying to RF for visualization example)
connected = corn_only_RF.connectedPixelCount(50)
filtered = corn_only_RF.updateMask(connected.gte(10))

# Visualization with geemap
Map = geemap.Map()
Map.centerObject(aoi, 15)
Map.setOptions('HYBRID')

# Add layers
Map.addLayer(cluster_image, {
    'min': 0,
    'max': 4,
    'palette': ['red', 'blue', 'green', 'orange', 'purple']
}, 'Clusters')

# Map.addLayer(corn_only_RF.clip(aoi), {'palette': ['yellow']}, 'Corn (Random Forest)')
Map.addLayer(corn_only_SVM.clip(aoi), {'palette': ['green']}, 'Corn (Support Vector Machine)')
# Map.addLayer(filtered.clip(aoi), {'palette': ['lime']}, 'Corn (Filtered)')

s2_median = s2_raw.median()
Map.addLayer(s2_median, {'bands': ['B4','B3','B2'], 'max': 3000}, 'True Color')

# Display map
Map

# Export to Google Drive (Optional)

# Uncomment เพื่อ export ผลลัพธ์
task = ee.batch.Export.image.toDrive(
    image=filtered,
    description='corn_classification_2024',
    scale=10,
    region=aoi,
    fileFormat='GeoTIFF',
    maxPixels=1e9
)
task.start()
print('\nExport task started. Check your Google Drive.')

"""#ดูว่า cluster ไหนมีจริง"""

import ee
import pandas as pd

# ดึงข้อมูล
clusterHist = cluster_image.reduceRegion(
    reducer=ee.Reducer.frequencyHistogram(),
    geometry=aoi,
    scale=10,
    maxPixels=1e9,
    bestEffort=True
)

cluster_data = clusterHist.getInfo()['cluster']

# แปลงเป็น DataFrame
df = pd.DataFrame([
    {
        'Cluster': int(cluster_id),
        'Area_sqm': area,
        'Area_hectares': area / 10000,
        'Area_rai': area / 1600
    }
    for cluster_id, area in cluster_data.items()
])

# คำนวณเปอร์เซ็นต์
total_area = df['Area_sqm'].sum()
df['Percentage'] = (df['Area_sqm'] / total_area) * 100

# เรียงลำดับจากมากไปน้อย
df = df.sort_values('Area_hectares', ascending=False).reset_index(drop=True)

# แสดงผล
print('='*80)
print('Cluster Distribution Summary')
print('='*80)
print(df.to_string(index=False))
print('='*80)
print(f"\nTotal Area: {total_area/10000:,.2f} hectares ({total_area/1600:,.2f} rai)")
print('='*80)

# วาดกราฟ (ถ้ามี matplotlib)
try:
    import matplotlib.pyplot as plt

    plt.figure(figsize=(10, 6))
    plt.bar(df['Cluster'].astype(str), df['Area_hectares'], color='skyblue', edgecolor='black')
    plt.xlabel('Cluster ID', fontsize=12)
    plt.ylabel('Area (Hectares)', fontsize=12)
    plt.title('Cluster Distribution by Area', fontsize=14, fontweight='bold')
    plt.grid(axis='y', alpha=0.3)

    # เพิ่ม label เปอร์เซ็นต์
    for i, row in df.iterrows():
        plt.text(i, row['Area_hectares'],
                f"{row['Percentage']:.1f}%",
                ha='center', va='bottom')

    plt.tight_layout()
    plt.show()
except ImportError:
    print("ติดตั้ง matplotlib เพื่อดูกราฟ: pip install matplotlib")

# Assuming 'training' FeatureCollection is available from previous steps
# If not, re-run the cell that creates 'training' or include its definition here.

# Get the class distribution from the training data
class_distribution = training.aggregate_histogram('class').getInfo()

print('='*50)
print('Training Data Class Distribution')
print('='*50)

if class_distribution:
    total_samples = sum(class_distribution.values())
    print(f"Total Training Samples: {total_samples:,}")
    print("-" * 50)

    # Sort by class ID
    sorted_classes = sorted(class_distribution.items(), key=lambda item: int(item[0]))

    for class_id, count in sorted_classes:
        percentage = (count / total_samples) * 100 if total_samples > 0 else 0
        class_name = 'Non-Corn' if int(class_id) == 0 else 'Corn'
        print(f"Class {class_id} ({class_name}): {count:,} samples ({percentage:.2f}%)")
else:
    print("No training data found.")

print('='*50)